server:
  port: 8050
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gatewayzool
zuul:
  routes:
    order-serviceId:
      path: /order/**
      service-id: eureka-order
