
server:
  port: 8000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
      enable-self-preservation: true
spring:
  application:
    name: eureka-user
